# Generated by Django 4.2.10 on 2024-03-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataInventory', '0002_product_categorias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='caracteristicas',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='product',
            name='codigo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='moneda',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
