# Generated by Django 4.2.10 on 2024-03-03 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataInventory', '0003_rename_description_product_caracteristicas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='done',
        ),
    ]
