# Generated by Django 4.2.10 on 2024-03-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataInventory', '0004_remove_product_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categorias',
        ),
        migrations.AddField(
            model_name='product',
            name='categorias',
            field=models.ManyToManyField(to='dataInventory.categoria'),
        ),
    ]
