# Generated by Django 4.2.10 on 2024-03-04 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataInventory', '0006_cliente_ordenes_orden_ordenes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='ordenes',
        ),
    ]
