# Generated by Django 4.2.10 on 2024-03-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataInventory', '0007_remove_orden_ordenes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='ordenes',
        ),
        migrations.AddField(
            model_name='orden',
            name='ordenes',
            field=models.ManyToManyField(to='dataInventory.product'),
        ),
    ]
