# Generated by Django 4.2.10 on 2024-03-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataInventory', '0008_remove_cliente_ordenes_orden_ordenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ordenes',
            field=models.ManyToManyField(to='dataInventory.orden'),
        ),
    ]
