# Generated by Django 4.2.10 on 2024-03-04 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataInventory', '0009_cliente_ordenes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='ordenes',
        ),
    ]
