# Generated by Django 4.2.10 on 2024-03-04 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataInventory', '0010_remove_orden_ordenes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='cliente',
            new_name='nombre_pedido',
        ),
    ]
